pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {

                checkout scm
            }
        }
        
        stage('Install Requirements') {
            steps {
                sh 'pip install -r requirements.txt --break-system-packages'
            }
        }
        
        stage('Run Tests') {
            steps {

                sh 'python3 test.py'
            }
        }
    }
    

}
