pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {

                checkout scm
            }
        }
        
        stage('Install Requirements') {
            steps {
                sh 'pip install -r ./Task6-JenkinsFile/requirements.txt --break-system-packages'
            }
        }
        
        stage('Run Tests') {
            steps {

                sh 'python3 ./Task6-JenkinsFile/test.py'
            }
        }
    }
    

}
