name: Setup Docker Container && Image

on:
  push:
    branches: [ master ]

jobs:
  test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./Task 3 - GithubActions && Docker
      
      steps:
          - uses: actions/checkout@v3

          - name: Setting up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.9

          - name: Install dependencies
            run: |
              pip install -r Reqs.txt

          - name: Rubn Bash Script
            run: |
              bash Docker_Script.sh

          - run: echo "Action && Job Completed!"
